#ifndef PROTECT_FFI_H
#define PROTECT_FFI_H

#pragma once

/* Generated with cbindgen:0.26.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Client Client;

typedef struct CResult {
    bool success;
    const char *data;
    const char *error;
} CResult;

 struct CResult protect_new_client(const char *options_json) ;

 struct CResult protect_encrypt(const struct Client *client_ptr, const char *options_json) ;

 struct CResult protect_decrypt(const struct Client *client_ptr, const char *options_json) ;

 struct CResult protect_encrypt_bulk(const struct Client *client_ptr, const char *options_json) ;

 struct CResult protect_decrypt_bulk(const struct Client *client_ptr, const char *options_json) ;


struct CResult protect_decrypt_bulk_fallible(const struct Client *client_ptr,
                                             const char *options_json)
;

 void protect_free_client(const struct Client *client_ptr) ;

 void protect_free_string(const char *str_ptr) ;

#endif /* PROTECT_FFI_H */
